# Generated by Django 3.2 on 2021-04-26 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truequeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('N', 'Nuevo'), ('SN', 'Semi nuevo'), ('U', 'Usado')], max_length=2)),
                ('categoria', models.CharField(choices=[('Ac', 'Accesorios'), ('AE', 'Aparatos Electronicos'), ('AF', 'Audio/Foto'), ('AJ', 'Artesania/Joyeria'), ('Cm', 'Camping'), ('Dp', 'Deportes'), ('Hr', 'Herramientas'), ('HM', 'Hogar/Muebles'), ('Jg', 'Juguetes'), ('MP', 'Materia prima'), ('MI', 'Musica/Instrumentos'), ('Lb', 'Libros'), ('PS', 'Peliculas/Series'), ('Rp', 'Ropa'), ('Sl', 'Salud'), ('Tc', 'Tecnologia'), ('Vh', 'Vehiculos'), ('Ot', 'Otros')], max_length=2)),
                ('fotos', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('cambio', models.CharField(choices=[('Ac', 'Accesorios'), ('AE', 'Aparatos Electronicos'), ('AF', 'Audio/Foto'), ('AJ', 'Artesania/Joyeria'), ('Cm', 'Camping'), ('Dp', 'Deportes'), ('Hr', 'Herramientas'), ('HM', 'Hogar/Muebles'), ('Jg', 'Juguetes'), ('MP', 'Materia prima'), ('MI', 'Musica/Instrumentos'), ('Lb', 'Libros'), ('PS', 'Peliculas/Series'), ('Rp', 'Ropa'), ('Sl', 'Salud'), ('Tc', 'Tecnologia'), ('Vh', 'Vehiculos'), ('Ot', 'Otros')], max_length=2)),
                ('fecha', models.DateField(auto_now=True)),
                ('publicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
