# Generated by Django 3.2 on 2021-04-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truequeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fotos',
            field=models.ImageField(upload_to='publicaciones/%Y/%m/%d/'),
        ),
    ]
