# Generated by Django 3.2 on 2021-06-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truequeapp', '0002_auto_20210504_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='reputacion',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
