# Generated by Django 3.2 on 2021-04-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truequeapp', '0002_alter_publicacion_fotos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='fotos',
            new_name='foto_principal',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='foto_2',
            field=models.ImageField(default='', upload_to='publicaciones/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacion',
            name='foto_3',
            field=models.ImageField(default='', upload_to='publicaciones/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacion',
            name='foto_4',
            field=models.ImageField(default='', upload_to='publicaciones/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacion',
            name='foto_5',
            field=models.ImageField(default='', upload_to='publicaciones/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
