# Generated by Django 2.2.20 on 2021-06-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truequeapp', '0003_auto_20210608_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='truequesabiertos',
            name='estado',
            field=models.CharField(choices=[('A', 'Abierto'), ('C', 'Concretado'), ('F', 'Fallido')], default='A', max_length=1),
        ),
    ]
