# Generated by Django 3.2 on 2021-05-01 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truequeapp', '0003_auto_20210429_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruequesAbierto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interesado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truequeapp.publicacion')),
            ],
        ),
    ]
