# Generated by Django 3.2 on 2021-05-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truequeapp', '0004_truequesabierto'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='truequesabierto',
            constraint=models.UniqueConstraint(fields=('publicacion', 'interesado'), name='no repetir trueque'),
        ),
    ]
