# Generated by Django 2.2.20 on 2021-06-12 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truequeapp', '0004_truequesabiertos_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trueque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('A', 'Abierto'), ('C', 'Concretado'), ('F', 'Fallido')], default='A', max_length=1)),
                ('demandante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandante', to=settings.AUTH_USER_MODEL)),
                ('oferente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oferente', to=settings.AUTH_USER_MODEL)),
                ('publicacion_demandante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicacion_demandante', to='truequeapp.Publicacion')),
                ('publicacion_oferente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicacion_oferente', to='truequeapp.Publicacion')),
            ],
        ),
        migrations.DeleteModel(
            name='TruequesAbiertos',
        ),
        migrations.AddConstraint(
            model_name='trueque',
            constraint=models.UniqueConstraint(fields=('publicacion_oferente', 'publicacion_demandante'), name='no repetir trueque'),
        ),
    ]
