# Generated by Django 3.2 on 2021-05-01 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truequeapp', '0005_truequesabierto_no repetir trueque'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TruequesAbierto',
            new_name='TruequesAbiertos',
        ),
    ]
