# Generated by Django 3.2 on 2021-06-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truequeapp', '0008_alter_mensaje_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='tipo',
            field=models.CharField(choices=[('C', 'calificar'), ('R', 'revisar'), ('A', 'aceptar')], max_length=1),
        ),
    ]
