# Generated by Django 3.2 on 2021-06-17 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truequeapp', '0010_alter_mensaje_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensaje',
            options={'ordering': ['-fecha_de_envio']},
        ),
    ]
