# Generated by Django 3.2 on 2021-06-17 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truequeapp', '0007_auto_20210614_1712'),
        ('truequeapp', '0011_alter_mensaje_options'),
    ]

    operations = [
    ]
