# Generated by Django 2.2.20 on 2021-06-20 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truequeapp', '0015_clasificacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clasificacion',
            new_name='Calificacion',
        ),
    ]
