# Generated by Django 3.2 on 2021-06-21 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truequeapp', '0003_usuario_reputacion'),
        ('truequeapp', '0014_auto_20210618_1934'),
        ('truequeapp', '0016_auto_20210620_1718'),
    ]

    operations = [
    ]
