# Generated by Django 3.2 on 2021-06-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truequeapp', '0017_merge_20210620_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='reputacion',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
