# Generated by Django 3.2 on 2021-06-30 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truequeapp', '0018_auto_20210622_1432'),
        ('truequeapp', '0018_auto_20210622_2357'),
    ]

    operations = [
    ]
